### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by TeeKay1** [yPedx/SB-GUI#16]
I just had a suggestion about some commands. Mainly adding in "tempban #target (time) Reason." There are things that dont need to be a perma ban but longer than a kick. You would be awesome to do this.

**Comment by yPedx** [comment]
Simply change the command for the item to tempban instead :D The commands are not from SB-GUI, but other plugins. This plugin is only a GUI with items you can assign commands to.

**Comment by TeeKay1** [comment]
hmmm
i tried to setup a tempban but it didnt work...i have smite and tempban on the same item and it smited but didnt tempban. Thats why im confused.

**Comment by yPedx** [comment]
Please post your config file using [pastebin.com](https://pastebin.com/)

**Comment by TeeKay1** [comment]
https://pastebin.com/EMriVnB5

**Comment by yPedx** [comment]
Please check that you are using the correct format. And I'm going on a holiday for 2 weeks, I won't be able to fix any upcoming bugs if there are any.

**Comment by yPedx** [comment]
Does the issue still remain, or has it been solved?

**Comment by TeeKay1** [comment]
Yup i got it working. It was just a formatting error.

**Comment by TeeKay1** [comment]
Is there a way i can ban across all servers?

**Comment by yPedx** [comment]
You'll have to set a global ban command for that then ;)
