### ISSUE TITLE
Removing stats item.,

### ISSUE THREAD

**Issue by Sytanicy** [yPedx/SB-GUI#21]
Hi yPedx,
How to remove the stats item sign,

~Sytanicy

**Comment by yPedx** [comment]
I apologize, this is not a feature yet :/ Would be a great suggestion though!

**Comment by Sytanicy** [comment]
Like this: 
https://gyazo.com/634462c60c93d43152fc0a4f297dbf84

**Comment by yPedx** [comment]
What exactly do you mean?

**Comment by Sytanicy** [comment]
Just like a skull instead of a star, and that you can see the punishments (That book on the top line)

**Comment by Sytanicy** [comment]
I mean move* with my first question

**Comment by yPedx** [comment]
Stats item as a skull, and that you can move it? Would be great :D Might become a feature as well as moving the other standard items.

**Comment by Sytanicy** [comment]
And that you can see all the punishments ?

**Comment by yPedx** [comment]
I'll see what I can do when I get back from my holiday (Friday).
