### ISSUE TITLE
Error when i try to edit

### ISSUE THREAD

**Issue by pZeno** [yPedx/SB-GUI#22]
When i try to edit the gui adding the first random item like "DIRT", it gives me the error when i try to open it 

Error: An internal error occurred while attempting to perform this command
Link config: https://pastebin.com/dVeST5s5

**Comment by yPedx** [comment]
I forgot, you need to post the whole error using pastebin too. :p

**Comment by pZeno** [comment]
Error: https://pastebin.com/H9PVrCiz
Look spigot private message

**Comment by yPedx** [comment]
mhh, seems like another 1.7 compabillity problem, I'll be on it as soon as I can.

**Comment by yPedx** [comment]
Found the issue, 1.7 will be brought back in future versions.
