### ISSUE TITLE
Dont know how to add name

### ISSUE THREAD

**Issue by deputydirtbag** [yPedx/SB-GUI#23]
how do I add a name to my command. like /kill [name]

**Comment by yPedx** [comment]
You may find information about this on the spigot download page under the "NOTE" section. - https://www.spigotmc.org/resources/sb-gui-%E2%9D%96-advanced-punishment-gui-%E2%9D%96-make-your-own-custom-punishment-gui.38443/

Variables: #target, #punisher, #reason
Use #target for the player you want to punish/affect.

**Comment by yPedx** [comment]
You may find information about this on the spigot download page under the "NOTE" section. - https://www.spigotmc.org/resources/sb-gui-%E2%9D%96-advanced-punishment-gui-%E2%9D%96-make-your-own-custom-punishment-gui.38443/

Variables: #target, #punisher, #reason
Use #target for the player you want to punish/affect.
